// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "./header/header"
// import { MantineProvider } from '@mantine/core';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <MantineProvider withGlobalStyles withNormalizeCSS>
//           <Header />
//           {children}
//         </MantineProvider>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header/header";
import '@mantine/core/styles.css'; 
import { MantineProvider } from "@mantine/core";

// Google fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ SEO Metadata
export const metadata: Metadata = {
  title: "Interview Questions, Career Tips & Resume Advice | CareerCrack",
  description:
    "Get expert-curated interview questions, career advice, and resume tips to prepare for tech jobs and ace your interviews.",
  keywords: [
    "interview questions",
    "career advice",
    "resume tips",
    "job preparation",
    "HR tips",
    "interview preparation",
    "career growth",
    "coding interview",
    "technical interview",
  ],
  authors: [{ name: "Interview Question", url: "https://careercrack.com" }],
  creator: "CareerCrack",
  metadataBase: new URL("https://careercrack.com"),
  openGraph: {
    title: "Interview Questions, Career Tips & Resume Advice | CareerCrack",
    description:
      "Explore real-world interview questions, expert career tips, and resume strategies to help you land your dream job.",
    url: "https://careercrack.com",
    siteName: "CareerCrack",
    images: [
      {
        url: "https://careercrack.com/og-image.png",
        width: 1200,
        height: 630,
        alt: "Interview Questions & Career Tips",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Interview Questions, Career Tips & Resume Advice | CareerCrack",
    description:
      "Explore expert content on interview preparation, resume writing, and career guidance.",
    images: ["https://careercrack.com/og-image.png"],
    creator: "@careercrack",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider>
          <Header />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
